#server  .properties>>.yml
server:
  port: 80
  servlet:
    context-path: /
#HikarCP
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html 
  aop:
    proxy-target-class: false  #jdk Proxy (使用这个配置，会优先使用jdk代理，如果不行会自动转为CGLIB代理)
  task:
    execution:
      pool:
        queue-capacity: 128
        core-size: 1
        max-size: 128
        keep-alive: 60000
      thread-name-prefix: DB-SYS-Thread-
#mybatis
mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml
#thymeleaf
#log
logging:
  level:
    com.cy: debug
    